config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "home/index"
  root to: "home#index"

  get "dashboard", controller: "home", action: "dashboard", as: "dashboard"
  resources :posts do
    post :add_comment, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  accepts_nested_attributes_for :comments, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ActionController::Base
  layout "application"
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def dashboard
  end
end

app/controllers/posts_controller.rb
class PostsController < AuthenticatedController
  before_action :set_post, only: %i[ show edit update destroy add_comment ]
  before_action :set_comment, only: %i[ new edit  ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_comment
    set_comment

    respond_to do |format|
      # @post.set_attributes(post_params)
      # @post.comments.each do |comment|
      #   comment.user = current_user
      # end

      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :title, :comments_attributes)
    end

    def set_comment
      @post.comments.build
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/dashboard.html.erb
<h1>Welcome, this is user login home page</h1>

<button type="button"
        class="btn btn-lg btn-success"
        data-bs-toggle="popover"
        title="Popover title"
        data-bs-content="Amazing content, right ?">
        Click to toggle popover
</button>

<h2>Latest Posts</h2>

<%- if current_user.posts.empty? %>
  <h3>No posts yet</h3>
  <br/>
<%- else %>
  <%- current_user.posts.order(created_at: :desc).first(5).each do |post| %>
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <hr/>
  <% end %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome, this is the home page</h1>

<button type="button"
        class="btn btn-lg btn-danger"
        data-bs-toggle="popover"
        title="Popover title"
        data-bs-content="Amazing content, right ?">
        Click to toggle popover
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <%= link_to "Dashboard", dashboard_path %>

      <%- if current_user.present? %>
        <%= link_to "New post", new_post_path %>
        <%= link_to "All posts", posts_path %>
        <%= button_to "Sair", destroy_user_session_path, method: :delete %>
      <% end %>
    </header>

    <div class="flash-notice"><%= notice %></div>
    <div class="flash-alert"><%= alert %></div>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |post_form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= post_form.label :title, style: "display: block" %>
    <%= post_form.text_field :title %>
  </div>

  <div>
    <%= post_form.label :body, style: "display: block" %>
    <%= post_form.text_area :body %>
  </div>

  <turbo-frame id="<%= post_form.field_id(:comments) %>" class="contents">
    <%= post_form.fields_for :comments do |comment_form| %>
      <div class="flex gap-2">
        <%= comment_form.hidden_field :user_id, value: post_form.object.user_id %>

        <div class="text-sm text-right"> <%= comment_form.object&.id || "New comment" %> </div>
        <%= comment_form.text_area :body, placeholder: "Add your comment here" %>
      </div>
    <% end %>

    <div class="flex gap-2">
      <%- if post_form.object.comments.map(&:id).compact_blank %>
        <p>No comments</p>
      <% else %>
        <%- post_form.object.comments.each do |comment| %>
          <%- if comment.id %>
            <div class="text-sm text-right"> Author: <%= comment.user.name %> </div>
            <div class="text-sm text-right">
              <p>Body:</p>
              <%= comment.body %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </turbo-frame>

  <%= post_form.submit "Add comment",
      formmethod: "post",
      formaction: add_comment_post_path(id: post_form.object),
      data: { turbo_frame: post_form.field_id(:comments) },
      name: :add_comment %>

  <div>
    <%= post_form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>